# Site settings
name: suncover
email: wxrcourage@foxmail.com
author: Wang xiaorui
url: 
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/suncover/
baseurl: 
description: Veni Vidi Vici
meta_description: 王晓瑞
motto: thinking
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: suncover

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

